### simple chat
POST http://localhost:8080/chat
Content-Type: text/plain

What's Java?

### ChatGPT translation
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{openai_api_key}}
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "I want you to act as an English to Chinese translator."
    },
    {
      "role": "user",
      "content": "Hello, how are you?"
    }
  ]
}

### ChatGPT function call
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{OPENAI_API_KEY}}
Content-Type: application/json

{
  "model": "gpt-3.5-turbo-0613",
  "messages": [
    {
      "role": "user",
      "content": "Give me a simple Java example, and compile the generated source code."
    }
  ],
  "functions": [
    {
      "name": "compile_java",
      "description": "Compile Java source file",
      "parameters": {
        "type": "object",
        "properties": {
          "source": {
            "type": "string",
            "description": "java file name or source code"
          }
        },
        "required": [
          "source"
        ]
      }
    }
  ]
}